name:                webex-teams-conduit
version:             0.2.0.0
github:              "nshimaza/webex-teams-api"
license:             MIT
author:              "Naoto Shimazaki"
maintainer:          "Naoto.Shimazaki@gmail.com"
copyright:           "2017,2018 Naoto Shimazaki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Conduit wrapper of Webex Teams List API
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nshimaza/webex-teams-api#readme>

dependencies:
- base >= 4.7 && < 5
- conduit
- webex-teams-api

library:
  source-dirs: src

executables:
  webex-teams-conduit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webex-teams-conduit
    - bytestring
    - data-default
    - http-client
    - optparse-applicative
    - text
    - utf8-string

tests:
  webex-teams-conduit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - webex-teams-conduit
    - aeson
    - async
    - bytestring
    - data-default
    - http-conduit
    - http-types
    - network-uri
    - text
    - wai
    - warp
    - hspec
